---

- name: Ensure bind is started and enabled on boot
  service:
    name:    '{{ bind__service_name }}'
    enabled: '{{ bind__service_enabled|bool }}'
    state:   "{{ bind__service_enabled|bool|ternary('started', 'stopped') }}"
